google/flutter-desktop-embedding

- macos/example/Example Embedder.xcodeproj/project.pbxproj
- macos/example/ExampleWindow.swift
- macos/library/FLEViewController.h
- macos/library/FLEViewController.m
The embedding API allows passing empty main and package paths to use
snapshot mode rather than source mode, which allows for easy bundling.
Switches the example app to use snapshot mode, and bundles the build
resources directory, so that the app is self-contained. Removes the
need for the command-line argument workaround (which was accidentally
missing from the previous patch due to the scheme that passed the path
to the example app directory not being marked as shared, so this has
the added effect of fixing the sample app).
Closes #8
> Add support for snapshot mode to FLEViewController

- macos/library/FLEOpenGLContextHandling.h
- macos/library/FLEView.m
- macos/library/FLEViewController.m
Creates an NSOpenGLContext sharing with the view's OpenGLContext,
and makes it available to the engine via the new resource context
callback.
Closes #19
> Add a resource context on macOS

- linux/example/Makefile
- linux/library/Makefile
Fixes issue #19: moving the link statements to the end of the flag
declarations appears to fix the build issue.
> Makefile update.

- macos/example/Base.lproj/MainMenu.xib
- macos/library/FLEViewController.m
The pixel ratio was hard-coded to 1.0; this uses the actual
pixel ratio, and enables high-resolution support on the OpenGL view.
macOS portion of Issue #32
> Use actual pixel ratio on macOS

- linux/example/Makefile
- macos/example/Example Embedder.xcodeproj/project.pbxproj
'flutter build flx' no longer does anything, and has been replaced by
'flutter build bundle'. Update the builds accordingly.
> Update the 'flutter build' command

- tools/update_flutter_engine
A clean Flutter doesn't contain Dart; check whether Dart is present
before trying to use it, and if not run 'flutter precache'.
Fixes issue #63
> Ensure Dart is present in update_flutter_engine

- linux/.gitignore
- linux/README.md
- linux/example/Makefile
- linux/example/flutter_embedder_example.cc
- linux/library/Makefile
- linux/library/include/flutter_desktop_embedding/channels.h
- linux/library/include/flutter_desktop_embedding/embedder.h
- linux/library/include/flutter_desktop_embedding/plugin.h
- linux/library/src/embedder.cc
Instead of requiring that the Linux engine be manually added to the tree,
fetch the correct prebuilt version automatically as is done on macOS.
Updates the source to expect the engine's header to be called
flutter_embedder.h, as that is what it is named in the archive. The
desktop embedding header has been renamed from flutter_embedder.h
to just embedder.h to avoid confusion.
> Use update_flutter_engine in the Linux build

- macos/example/AppDelegate.swift
The application is not multi-window, so it should quit when the window
is closed.
> [macOS] Quit the example app when closing the window

- README.md
- linux/README.md
- macos/README.md
- plugins/README.md
Removes stale information, moves common setup and discussion
to the top-level README, improves consistency between macOS
and Linux README structure, and makes it somewhat more
evergreen by reducing discussion of specific things that are
not implemented (since those things have tended to become
stale quickly).
Also adds some new documentation, including a repository
structure overview.
> Overhaul the READMEs

- example_flutter/lib/main.dart
- example_flutter/pubspec.lock
This makes it easy to test basic text input support from the example
applications on each platform.
Includes two widgets since at some point in the future we can
hopefully support tabbing between fields, so having two will
be useful for testing.
> Add input fields to example app

- linux/library/src/text_input_model.cc
Fixes a boolean that was incorrectly given a value of 0
instead of false, which caused type errors under Dart2.
Fixes #65
> [linux] Fix text editing state type

- README.md
- linux/.gitignore
- linux/example/Makefile
- linux/example/flutter_embedder_example.cc
- linux/library/Makefile
- macos/example/Example Embedder.xcodeproj/project.pbxproj
- macos/library/FlutterEmbedderMac.xcodeproj/project.pbxproj
- tools/flutter_location
- tools/update_flutter_engine
Requiring the Flutter tree to be in a specific location is problematic
for client projects that need to control layouts (e.g., need to map
Flutter at another location for other reasons), and also makes it
difficult for individuals to share the tree used for this project with
other uses of Flutter.
To improve flexibility, allow a .flutter_location_config file in the
directory containing this repository (not inside it, so that it can be
checked in to an enclosing repository if desired) that specifies the
location of the Flutter tree.
> Add a configuration option for Flutter location

- tools/update_flutter_engine.bat
Allows easily running update_flutter_engine on Windows.
For now, since flutter_location isn't ported yet, uses a
hard-code directory for the flutter tree the way the other
platforms used to.
> Add a .bat version of update_flutter_engine

- README.md
- example_flutter/lib/main.dart
Flutter no longer maps desktop host platforms to mobile target
platforms, and instead throws 'Unknown platform' exceptions.
This adds a debugDefaultTargetPlatformOverride to bypass the
detection logic so that the example runs on desktop.
Also updates the main README to include a section on likely pitfalls
when attempting to run a stock Flutter application on desktop (so far,
this issue and font handling), along with suggested solutions.
> Set debugDefaultTargetPlatformOverride

- linux/library/Makefile
- linux/library/include/flutter_desktop_embedding/channels.h
- linux/library/include/flutter_desktop_embedding/embedder.h
- linux/library/include/flutter_desktop_embedding/plugin.h
- linux/library/src/channels.cc
- linux/library/src/embedder.cc
- linux/library/src/internal/keyboard_hook_handler.h
- linux/library/src/internal/plugin_handler.cc
- linux/library/src/internal/plugin_handler.h
- linux/library/src/internal/text_input_model.cc
- linux/library/src/internal/text_input_model.h
- linux/library/src/internal/text_input_plugin.cc
- linux/library/src/internal/text_input_plugin.h
- linux/library/src/plugin.cc
Various minor cleanup to the Linux library source:
- Moves code (both implementation and headers) that's only intended for
use by the embedding library, rather than clients of it, into a new
src/internal.
- Standardizes include format: For public headers, use relative paths in
quotes, to ensure the correct files are used. For everything else, use
standard Google style of full path from repository root.
- Fixes a few include guards that didn't match the file path.
> Linux library file cleanup

- linux/library/include/flutter_desktop_embedding/method_call.h
- linux/library/include/flutter_desktop_embedding/method_result.h
- linux/library/include/flutter_desktop_embedding/plugin.h
- linux/library/src/embedder.cc
- linux/library/src/method_call.cc
- linux/library/src/method_result.cc
Splits MethodCall and MethodResult into separate files. This follows the
more usual C++ convention of having one file per class, and makes the
code structure more consistent with the Android Flutter plugin
implementation (vs. following the iOS file structure, as it did before).
This is purely a move of code, with no implementation changes.
It is a precursor to the next plugin refactor, to avoid having
substantial functionality change mixed with file moves.
JsonMethodResult is left with MethodResult since it will be eliminated
in the refactor anyway.
> [linux] Split channels.h into separate files

- macos/library/FLEViewController.h
- macos/library/FLEViewController.m
- macos/library/FlutterEmbedderMac.h
- macos/library/FlutterEmbedderMac.xcodeproj/project.pbxproj
Miscellaneous cleanup for the macOS embedding framework:
- Make FLEViewController's conformance to FLEReshapeListener public
since that would be necessary for a non-FLEView view implementation.
- Update files in Xcode so that only public headers are in the Public
group
- Reorganize FLEViewController's methods so that the #pragma groupings
are accurate, and so that the definition orders match the declaration
orders.
- Declare all private methods expplicitly in the class extension, and
move all declaration comments there, to make the internal API surface
clearer.
- Remove nullability annotations from the implementations, since they
are intended for interfaces and mismatches can be problematic.
- Rename "theEvent" to "event" to match normal variable naming practice.
> macOS library code cleanup

- linux/example/flutter_embedder_example.cc
- linux/library/include/flutter_desktop_embedding/embedder.h
- linux/library/src/embedder.cc
- macos/example/ExampleWindow.swift
- windows/example/flutter_embedder_example.cpp
- windows/library/embedder.cpp
- windows/library/embedder.h
Since the example apps should show best practice, only enable
--dart-non-checked-mode for release builds. This also makes it easier
to do proper testing of Flutter framework and/or engine changes using
the example app.
On Windows and Linux, updated the launch APIs to take a vector of
strings to make it easier to manage optional arguments.
> Enable checked mode for debug builds

- linux/example/Makefile
- macos/example/Example Embedder.xcodeproj/project.pbxproj
- tools/build_flutter_assets
- tools/build_flutter_assets.bat
- windows/scripts/build_example_app.bat
This consolidates the logic for creating the flutter_assets directory in
a central location, rather than it being embedded into each
platform-specific project. Benefits:
- Easier to update if the command changes, as happend with the change
from flx to bundle. Clients can use this script and be insulated from
any such changes in the future.
- Easier to understand the details of what's run without having to find
it in the native projects (e.g., in Xcode, where it's non-trivial to
find especially for people not familiar with Xcode's UI).
- Easier to change to a local engine build for testing, due to including
the necessary flags as commended-out variables. (In the future, if
it's sufficient useful, the scripts could be extended to take a config
file as with Flutter location.)
> Add a wrapper script for 'flutter build bundle'

- macos/library/FLEViewController.m
Moves internal plugin registration to just before the engine starts
rather than during init, to avoid the complexity of having plugin
registration potentially happening during init.
Also moves common ivar initialization from an ObjC method to a static
function, which is a safer pattern as it isn't subject to naming
collisions in subclasses.
> [macos] Simplify view controller initialization

- macos/library/FLEChannels.h
- macos/library/FLEChannels.m
- macos/library/FLECodecs.h
- macos/library/FLEMethods.h
- macos/library/FLEMethods.m
- macos/library/FlutterEmbedderMac.h
- macos/library/FlutterEmbedderMac.xcodeproj/project.pbxproj
Moves FLEMethodCall and FLEMethodError out of Channels.h. This better
aligns with the Flutter iOS structure, although this deviates in that on
iOS these classes live in the Codecs.* files, while this keeps them
separate to reduce the number of classes being declared in a single
header.
Preparation for the remaining plugin refactoring (which adds channel
classes to the Channels.* files).
> [macos] Move FLEMethodCall and FLEMethodError

- macos/library/FLEBinaryMessenger.h
- macos/library/FLEChannels.h
- macos/library/FLEChannels.m
- macos/library/FLEViewController.h
- macos/library/FLEViewController.m
- macos/library/FlutterEmbedderMac.h
- macos/library/FlutterEmbedderMac.xcodeproj/project.pbxproj
Adds the MethodChannel class, and the accompanying BinaryMessegener
protocol, for parity with the existing iOS Flutter plugin/channel
structure.
This lays the foundation for a future breaking change that makes plugin
creation and registration match the iOS structure, but for now makes the
method channel an internal implementation detail of the existing plugin
messaging design to preserve compatibiility.
> [macos] Add MethodChannel

- library/linux/include/flutter_desktop_embedding/binary_messenger.h
- library/linux/include/flutter_desktop_embedding/plugin.h
- library/linux/src/embedder.cc
- library/linux/src/internal/plugin_handler.cc
- library/linux/src/internal/plugin_handler.h
- library/linux/src/plugin.cc
Adds the BinaryMessanger interface, containing only the send API for
now. This eliminates the engine pointer from a public header, and is a
small step toward moving toward supporting MessageChannel/MethodChannel.
Technically this is a breaking change, but there's no expectation that
any code outside of the library would be using set_engine, so should not
actually impact anyone.
Part of issue #102.
> [linux] Add the beginning of BinaryMessenger

- library/linux/include/flutter_desktop_embedding/json_method_codec.h
- library/linux/src/internal/json_message_codec.cc
- library/linux/src/internal/json_message_codec.h
- library/linux/src/json_method_codec.cc
Separates the basic JSON<->byte stream logic out into JsonMessageCodec,
which is an eventual part of the final channel interface.
Eventually this class will inherit from a generic MessageCodec
interface, but in order to make this functionality available for library
use while the type handling of the public interface is worked out, the
new class is internal for now.
> Split JsonMessageCodec out from JsonMethodCodec

- library/linux/include/flutter_desktop_embedding/binary_messenger.h
- library/linux/include/flutter_desktop_embedding/json_plugin.h
- library/linux/include/flutter_desktop_embedding/method_channel.h
- library/linux/include/flutter_desktop_embedding/plugin.h
- library/linux/src/embedder.cc
- library/linux/src/internal/engine_method_result.cc
- library/linux/src/internal/engine_method_result.h
- library/linux/src/internal/plugin_handler.cc
- library/linux/src/internal/plugin_handler.h
- library/linux/src/json_plugin.cc
- library/linux/src/method_channel.cc
- library/linux/src/plugin.cc
This adds the MethodChannel and related APIs on Linux, further aligning
with the Flutter APIs. As with the current state on macOS, this is
implemented as an implementation detail of the existing plugin classes,
so that there's no plugin API breakage at this stage.
This currently deviates from the MethodChannel API on other platforms by
using InvokeMethodCall instead of InvokeMethod. Addressing this will be
done in a follow-up change.
Part of issue #102
> [linux] Add MethodChannel

- .gitignore
- .gn
- BUILD.gn
- build/BUILD.gn
- build/BUILDCONFIG.gn
- build/flutter.gni
- build/linux/config/BUILD.gn
- build/packaging.gni
- example/linux/Makefile
- library/BUILD.gn
- library/GN.md
- library/README.md
- library/engine.gni
- library/linux/BUILD.gn
- plugins/color_panel/BUILD.gn
- plugins/file_chooser/BUILD.gn
- plugins/menubar/BUILD.gn
- third_party/chromium/LICENSE
- third_party/chromium/build/config/linux/pkg_config.gni
- third_party/chromium/build/toolchain/BUILD.gn
- tools/dart_tools/bin/pkg_config.dart
- tools/gn_dart
Adds an experimental GN-based build as an alternative to the Make-based
build on Linux.
The example application does not use GN for its own build since it is
intended to serve as an example of using the embedding library, so it
continues to use the more common Make as clients are unlikely to be
using GN.
First step toward possible approach to #114
> Initial Linux GN build

- example/flutter_app/lib/main.dart
- plugins/color_panel/common/channel_constants.cc
- plugins/color_panel/common/channel_constants.h
- plugins/color_panel/lib/color_panel.dart
- plugins/color_panel/linux/src/color_panel_plugin.cc
- plugins/color_panel/macos/FLEColorPanelPlugin.mm
Left it as an optional parameter to mimic the native color choosers
> Adds opacity slider option to color panel

- Debugging.md
- README.md
Provides basic instructions for debugging the Flutter side of a desktop
application, since the normal approaches for Flutter debugging require
some modifications on desktop.
Related to issue #14 and issue #164, although doesn't fully address
either.
> Add initial debugging instructions

- example/macos/ExampleEmbedder.xcodeproj/project.pbxproj
Disable Xcode's default of automatically managing signing for the
example application, as this can cause issues for people who have a
developer team configured in Xcode.
Should address issue #178
> [macos] Disable automatic signing management

- README.md
Fixes dead WIKI docs link.
Awesome project btw
> Fixes dead link: Engine wiki URL has been moved

- CONTRIBUTING.md
Makes explicit what style guides and conventions the project follows, so that contributors can see them in advance rather than discovering them through the review process.
> Add project standards section to CONTRIBUTING.md

- Debugging.md
- example/linux/flutter_embedder_example.cc
- example/macos/ExampleWindow.swift
- example/windows/flutter_embedder_example.cpp
The Flutter engine renamed the flag that controls the "Debug" banner
as part of the Dart 2 transition (Engine PR 6977). Update the example
apps to pass the new flag in release mode.
> Update release mode flag

- .travis.yaml
- build/travis/install_flutter
- build/travis/linux/install_dependencies
- build/travis/linux/install_gn
- example/macos/ExampleEmbedder.xcodeproj/xcshareddata/xcschemes/ExampleEmbedder.xcscheme
Builds Linux via Make and GN, and builds macOS.
> Initial Travis configuration

- tools/build_flutter_assets
- tools/update_flutter_engine
Currently building is broken when there are spaces in the path
containing the local checkout of the repository.
> [macos] Fix script handling of spaces in paths

- library/common/glfw/embedder.cc
This PR adds pixel_ratio calculations to the GLFW embedder.
Fixes #32 
Replaces #187
> [glfw] Add dpi calculation to glfw embedder

- library/common/glfw/embedder.cc
small change, seems that `kDpPerInch` can be used in another instance so there's just one definition of the constant.
> [glfw] Use kDpPerInch in calculation

- example/windows/Example Embedder.sln
- example/windows/GLFW Example.vcxproj
- library/windows/Flutter Windows Embedder.sln
- library/windows/GLFW Library.vcxproj
> Remove VS Static Library Configs

- analysis_options.yaml
- example/flutter_app/analysis_options.yaml
- example/flutter_app/lib/keyboard_test_page.dart
- example/flutter_app/lib/main.dart
- plugins/color_panel/lib/color_panel.dart
- plugins/file_chooser/lib/src/channel_controller.dart
- plugins/menubar/lib/src/menu_channel.dart
- plugins/menubar/lib/src/menu_item.dart
- tools/dart_tools/bin/update_flutter_engine.dart
- Fixes the include path for the example app's analysis file, which
broke during the repository restructure.
- Removes analysis options that are obsolete in recent Dart versions.
- Fix some new analysis issues (mostly constructor ordering).
> Dart analysis-related fixes

- tools/dart_tools/bin/update_flutter_engine.dart
update_flutter_engine was broken by an incorrect change to try to fix an
analyzer warning that didn't end up getting turned on; the default value
is false, not null, for the help flag, so the test always passed.
> Revert incorrect change in update_flutter_engine.dart

- library/common/glfw/key_event_handler.h
The header guard for key_event_handler.h didn't actually work due to a
typo (k instead of K).
> Fix header guard

- library/windows/scripts/build_jsonlib.bat
- tools/dart_tools/bin/fetch_jsoncpp.dart
Re-adds checkout of jsoncpp to build_jsonlib.bat, so that a clean VS
build on Windows build will succeed. Makes fetch_jsoncpp.dart
handle the case where the clone has already been run, so that
it can be called unconditionally from build_json.bat.
Fixes a regression from PR #191
> Fix Windows VS build

- library/BUILD.gn
GN build fails as `exports.def` cannot be found.
> Remove exports.def from GN Build

- build/linux/config/BUILD.gn
- example/linux/Makefile
- library/BUILD.gn
- library/linux/Makefile
The makes libglfw added via pkg-config calls, rather than manually, for
consistency with other similar dependencies.
> [linux] Use pkg-config for libglfw

- LocalEngine.md
- README.md
- tools/build_flutter_assets
- tools/build_flutter_assets.bat
- tools/dart_tools/bin/build_flutter_assets.dart
- tools/dart_tools/bin/build_jsoncpp.dart
- tools/dart_tools/bin/fetch_jsoncpp.dart
- tools/dart_tools/bin/update_flutter_engine.dart
- tools/dart_tools/lib/flutter_utils.dart
- tools/dart_tools/lib/run_command.dart
update_flutter_engine and build_flutter_assets now check for an
engine_override file at the root of the repository to trigger the
use of a local engine. Updates the README to link to instructions
on using it.
Since this adds more logic to build_flutter_assets, it has been
rewritten in Dart.
There are some obvious limitations (e.g., hard-coded name/location
requirement, copying every time instead of only when the
local build has changed), which can be addressed in the future if
there's sufficient demand. Since it is only intended for temporary use
when debugging, or testing engine changes, this may be sufficient,
and is a significant improvement over managing it manually.
Unlike .flutter_location_config this has no leading ., and is in the
repository rather than above it. This difference …
> Add a simpler way to use a local Flutter engine

- library/GN.md
- tools/dart_tools/bin/fetch_jsoncpp.dart
- tools/dart_tools/lib/run_command.dart
Changes fetch_jsoncpp to use the main jsoncpp repository instead of the
clarkezone fork, now that the necessary VS support has landed in the
main repo.
Fixes current Windows build errors due to the previously-pinned commit
no longer existing due to a force-push in the forked repository.
Adds temporary logic to fetch_jsoncpp to try to fix up existing
checkouts. (Also removes the assertions that fetch_jsoncpp is being run
on Windows since it's not Windows-specific, and it's easier to maintain
if it can be run on any platform.)
> Update the source for fetch_jsoncpp

- example/linux/flutter_embedder_example.cc
- example/macos/ExampleWindow.swift
- example/windows/flutter_embedder_example.cpp
- library/common/glfw/embedder.cc
- library/include/flutter_desktop_embedding/glfw/embedder.h
- library/macos/FLEViewController.h
- library/macos/FLEViewController.m
- Eliminate the distinction between source mode and snapshot mode;
source mode hasn't worked since the switch to Dart2, and the relevant
engine arguments are deprecated in
https://github.com/flutter/engine/pull/7497
- Hide the need for the first argument to be the executable from clients
of the library; this is an implementation detail of the engine API,
and not something that each client application should need to handle
given that the expected use case is to provide a constructed argument
array, rather than pass through argc/argv directly.
(As part of this change, removes the macOS code to strip Xcode-added
arguments, for the same reason.)
This is a breaking change; clients will need to update the call to the
primary entry point, including removing the dummy first argument they
were …
> Simplify the API for launching Flutter

- library/macos/FLEViewController.m
Fix: https://github.com/google/flutter-desktop-embedding/issues/234
Update the bundle ID for FlutterEmbedder.framework to match the change at https://github.com/flutter/engine/pull/7503
> Updated bundle ID for FlutterEmbedder.framework

- library/macos/FLEViewController.m
Passes through the `NSEventModifierFlag` values for shift, option, control and command as Android `metaState` flags.
> add support for shift, option (alt), control and command (meta) modifier keys

- example/linux_fde/flutter_embedder_example.cc
- example/windows_fde/flutter_embedder_example.cpp
- library/common/glfw/embedder.cc
- library/macos/FLEViewController.m
Add error logging when starting the Flutter engine fails (on all
platforms), and on GLFW errors. Also exit early with error logging for
unrecoverable errors in the GLFW implementation.
Fixes #241.
> Add error logging to GLFW and Flutter setup

- example/README.md
- example/linux_fde/Makefile
- Clearly separates out and documents the variables that are most likely
to need to change if copying the example app.
- Better differentiate between paths that are relative to the example
and paths that are relative to the FDE repository, since apps using
FDE would not be expected to be in the same directory the way the
example is.
- Add a minimal "release" mode that enables that flag to disable Dart
asserts, as on macOS and Windows.
> [linux] Improve example Makefile

- Flutter-Requirements.md
- Quick-Start.md
- README.md
Adds documentation targetted at someone who has found the project hoping
to be able to run a command or two and have desktop support in their
existing Flutter application. Attempts to set expectations, but also
provide some more information about how someone could potentially get
started even without experience in desktop development.
> Address the 'How do I just use it' FAQ

- .appveyor.yml
- build/ci/install_flutter
- tools/dart_tools/bin/update_flutter_engine.dart
- tools/dart_tools/lib/flutter_utils.dart
- tools/dart_tools/lib/git_utils.dart
To minimize confusion, and reduce unnecessary issue reports, add a check
during builds that the Flutter tree being used is not older than the
last known point where there was a compatibility break. Instead of a
runtime error, or an unexplained build error, this will fail out during
the engine update step with a clear message to use a newer version of
Flutter.
Currently, this will ensure that people who aren't on Flutter master
will get an error message that's as clear as possible.
> Add Flutter tree min version check

- library/README.md
Call out the requirement that the library and the Flutter application
must be built with the same version, since some people have
started distributing binary versions apparently without being aware
of this.
> Add a warning about binaries to library README

- plugins/color_panel/macos/FLEColorPanelPlugin.mm
#231 
Also, ran clang-format on FLEColorPanelPlugin.mm
> [macOS] Use FLEMethodError on color panel plugin bad arguments

- library/common/glfw/embedder.cc
Avoids generating a UI that is too small in standard resolution monitors. #222
> [linux/windows] Cap the minimum pixel ratio to 1

- example/linux_fde/flutter_embedder_example.cc
- example/windows_fde/flutter_embedder_example.cpp
- library/BUILD.gn
- library/README.md
- library/common/glfw/flutter_window_controller.cc
- library/include/flutter_desktop_embedding/glfw/flutter_window_controller.h
- library/windows/GLFW Library.vcxproj
- library/windows/GLFW Library.vcxproj.filters
Creates a simple C++ object as the primary interaction point for the
embedder calls. This provides a simpler API surface than embedder.h,
and folds in some common code (e.g., error logging).
This also serves to insulate clients from the embedder.h API layer,
so that future incremental changes done for #230 will cause less churn
for embedders.
> [linux/windows] Add FlutterWindowController

- library/common/glfw/embedder.cc
- library/include/flutter_desktop_embedding/glfw/embedder.h
- library/include/flutter_desktop_embedding/glfw/flutter_window_controller.h
Rather than exposing the GLFWwindow that is used, treat it as an
implementation detail and use an opaque pointer specific to this library
as the context object instead.
In practice the use of GLFW can't be entirely internal since the use of
GLFW in the library prevents its use by the embedder, but the details of
how it is used should not be exposed. This also gives greater control
over the API surface, as part of working toward a stable ABI (#230).
This does mean that the embedder cannot manipulate the GLFW window
directly, but rather than trust that doing so would be safe across DLL
boundaries, any functionality need by the simple embedder
use cases this library enables should be exposed via wrappers.
> Remove GLFW from the API surface

- library/macos/FLEViewController.mm
- library/macos/FlutterEmbedderMac.xcodeproj/project.pbxproj
https://github.com/flutter/engine/pull/7567 renamed the type of the
result for embedding API calls. Rather than force a Flutter upgrade by
using the new type name, temporarily use 'auto' for the type (with a
TODO to change it later, since auto is arguably less readable here).
This requires converting the file to ObjC++, which required a few
explicit casts in places that were previously being silently recast.
> [macos] Adjust for embedding API type name change

- library/BUILD.gn
- library/common/glfw/embedder.cc
- library/common/glfw/flutter_window_controller.cc
- library/common/internal/incoming_message_dispatcher.cc
- library/common/internal/incoming_message_dispatcher.h
- library/common/internal/plugin_handler.cc
- library/common/internal/plugin_handler.h
- library/include/flutter_desktop_embedding/glfw/embedder.h
- library/include/flutter_desktop_embedding/glfw/flutter_window_controller.h
- library/windows/GLFW Library.vcxproj
- library/windows/GLFW Library.vcxproj.filters
Eliminates PluginRegistrar and BinaryMessenger from the embedder.h API
surface, moving them up to the FlutterWindowController level. In their
place, adds new low-level messaging APIs, which are based closely on
the Flutter engine embedder APIs (including an equivalent message
struct), in some cases wrapping them directly. Unlike the engine APIs,
they allow per-channel callbacks, so individual plugins can use the API.
Since PluginHandler is no longer the source of truth for callback
registration, only an adaptor, it's now fine to have multiple instances
of them, all passing through to the underlying C API.
Part of #230
> [linux/windows] Separate out a C channel API

- library/GN.md
- library/README.md
The VS build also requires the VC build tools to be in the path (due to
running jsoncpp's build via script), so move the instructions from the
GN readme to the main readme.
> Move Windows PATH instructions

- library/common/glfw/embedder.cc
- library/common/glfw/flutter_window_controller.cc
- library/include/flutter_desktop_embedding/glfw/embedder.h
- library/include/flutter_desktop_embedding/glfw/flutter_window_controller.h
Remove remaining C++ from embedder.h, and add extern C. Since the
namespace is removed, use a standard prefix for all function names.
Part of #230
> Convert embedder.h to a C API

- build/win/toolchain/BUILD.gn
The link step includes the .lib file as output, but the link tool only
updates that file if something has changed, so it's possible to get into
situations where the .lib file is always older than the inputs, causing
the (expensive) link step to run every time.
This enabled ninja's 'restat' mode for the link step, so that it detects
the files that don't change and ignores them for the purposes of
determining what needs a rebuild.
> Add restat to Windows solink command

- example/README.md
- example/windows_fde/GLFW Example.vcxproj
- example/windows_fde/flutter_embedder_example.cpp
- example/windows_fde/scripts/build_example_app.bat
Copies the necessary Flutter data to a known location relative to the
executable, and uses executable-relative paths rather than
working-directory-relative paths.
This allows the executable to be run from any location, and makes it
clear what must be bundled as part of a working example. Follows the
same basic structure as the Linux example's bundling.
> Make the Windows example build self-contained

- example/macos_fde/ExampleEmbedder.xcodeproj/project.pbxproj
Since FlutterMacOS.framework is part of the bundled output, it makes
more sense to put it in SYMROOT (which is for build products) rather
than OBJROOT (which is for files used as part of the build process).
Fixes #282
> Use SYMROOT for framework download

- tools/run_dart_tool.bat
The error message from Windows when trying to run an executable that
doesn't exist isn't very helpful, so explicitly check that the Flutter
directory is actually there before trying to run flutter.
> Add error handling to run_dart_tool.bat

- tools/dart_tools/lib/flutter_utils.dart
Rolls the minimum version forward to pick up the new constants needed
for hover events.
> Update minimum Flutter version

- library/common/glfw/embedder.cc
The use of glfwWaitEvents() on Windows was incorrect, since there are
event sources such as plugin messages that GLFW is unaware of.
This will cause Windows to have the same high CPU usage as Linux, but
resolving that is a longer-term issue.
> Unify the GLFW event loop code

- example/macos/build.sh
This serves as a bridge to the new placeholder 'flutter build' support
for desktop.
> Add a build.sh for macOS

- example/macos/ExampleWindow.swift
- example/macos/PluginRegistrant.h
- example/macos/PluginRegistrant.m
- example/macos/Runner.xcodeproj/project.pbxproj
- tools/dart_tools/lib/flutter_utils.dart
Matches the structure of the iOS GeneratedPluginRegistrant. Uses ObjC,
rather than Swift, so that changes to add a new plugin are localized to
one file, instead of also affecting the bridging header.
This will make it easier to eventually transition to generated plugin
registration, and in the meantime makes it slightly easier to add
plugins manually.
> Move macOS plugin registration to a separate file

- example/macos/name_output.sh
This enables the placeholder 'flutter run' support; see
https://github.com/flutter/flutter/pull/31218
> Add name_output.sh for macOS

- example/windows/name_output.bat
The build directory is x64, not x86.
> Fix name_output.bat typo

- example/linux/Makefile
- example/linux/build.sh
- testbed/linux/Makefile
- testbed/linux/build.sh
- tools/dart_tools/bin/build_flutter_assets.dart
Plumbs the flag for enabling widget creation tracking from the build
script through to 'flutter build bundle'. Fixes the crash-on-hot-reload
in VS Code for Linux.
Since this was touching the build.sh/Makefile interaction, also plumbs
through FLUTTER_ROOT, although doesn't yet rely on it being there in the
example.
> Support --track-widget-creation on Linux

- .appveyor.yml
- .travis.yml
The builds are now dependent on files generated by the Flutter build
process, so the first build must be done with 'flutter build' rather than
direct build commands. This updates the CI scripts accordingly.
> Use 'flutter build' for CI

- example/windows/.gitignore
- example/windows/Runner.vcxproj
- example/windows/build.bat
- example/windows/generate_props.dart
- example/windows/scripts/build_example_app.bat
- testbed/windows/.gitignore
- testbed/windows/Runner.vcxproj
- testbed/windows/build.bat
- testbed/windows/generate_props.dart
- testbed/windows/scripts/build_example_app.bat
Plumbs the flag for enabling widget creation tracking from the build
script through to 'flutter build bundle'. Fixes the crash-on-hot-reload
in VS Code for Windows.
Since this added the logic to generate a property file for VS with
settings, also plumbs through FLUTTER_ROOT, although doesn't yet rely on
it being there in the example.
> Support --track-widget-creation on Windows

- example/macos/Runner.xcodeproj/project.pbxproj
Removes dependencies from example/macos/ on the FDE project, replacing the
flutter library sync with a manual copy.
This allows example/macos to be copied into an arbitrary Flutter project to
enable build/run for macOS. The dart code would of course still need changes
as described at:
https://github.com/flutter/flutter/wiki/Desktop-shells#flutter-application-requirements
> Make example/macos/ relocatable

- example/pubspec.yaml
This will help catch some errors caused by version mismatches that would
otherwise cause error messages that aren't at all self-explanatory.
This won't catch all cases, but for those that it does the failure will
be very early, and much clearer.
The intent is to rev this number every time a change is made on the
Flutter side that requires a corresponding change in this repository.
> Add a min Flutter version to the example

- LocalEngine.md
- example/linux/Makefile
- testbed/linux/Makefile
Brings testbed in line with the recent changes to example, supporting
--local-engine for testbed on Linux.
Includes a few tweaks to the example Makefile for some dependencies and
structure adjustments that I didn't notice in review of the earlier PR.
> Switch Linux testbed to tool_backend.sh

- plugins/example_plugin/analysis_options.yaml
- plugins/example_plugin/lib/example_plugin.dart
- plugins/example_plugin/linux/Makefile
- plugins/example_plugin/linux/example_plugin.cc
- plugins/example_plugin/linux/example_plugin.h
- plugins/example_plugin/pubspec.yaml
- testbed/lib/main.dart
- testbed/linux/Makefile
- testbed/linux/testbed.cc
- testbed/pubspec.yaml
Adds a trivial example plugin (currently Linux-only, but will support all platforms)
to serve as a starting point for new plugins, and a place to iterate on the
plugin build/management flow.
Linux part of #357
> Add an example plugin for Linux

- plugins/example_plugin/macos/.gitignore
- plugins/example_plugin/macos/Classes/FDEExamplePlugin.h
- plugins/example_plugin/macos/Classes/FDEExamplePlugin.m
- plugins/example_plugin/macos/ExamplePlugin.h
- plugins/example_plugin/macos/ExamplePlugin.xcodeproj/project.pbxproj
- plugins/example_plugin/macos/ExamplePlugin.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- plugins/example_plugin/macos/ExamplePlugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- plugins/example_plugin/macos/Info.plist
- testbed/lib/main.dart
- testbed/macos/PluginRegistrant.m
- testbed/macos/Runner.xcodeproj/project.pbxproj
For now this uses essentially the same structure as the other plugins,
although it doesn't use the shared project/framework copy, in order to
make it less closely tied to the FDE repo.
It still use the tools/ directory, but that will be eliminated as part
of migrating to CocoaPods in the future.
> Add example_plugin implementation for macOS

- example/macos/Runner.xcworkspace/contents.xcworkspacedata
- example/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- testbed/macos/Runner.xcworkspace/contents.xcworkspacedata
- testbed/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Since CocoaPods uses workspaces in its configuration, add them to the
proto-templates.
> Add Xcode workspaces to example and testbed

- example/linux/flutter_embedder_example.cc
- example/macos/ExampleWindow.swift
- example/windows/flutter_embedder_example.cpp
Make it more clear to people using the example little or no context that
there's currently no actual support for a release mode.
> Remove disabling of asserts from example runners

- example/windows/Runner.sln
- example/windows/Runner.vcxproj
- testbed/windows/Runner.vcxproj
The arguments to the helper commands were being quoted, but not the
commands themselves, causing failures if the path to the project had
spaces in it.
Also re-adds the previously-dropped example/Runner.sln, to make the
workflow smoother when opening the project in Visual Studio (to avoid
being prompted to save the auto-synthesized solution on quit).
Part of the fix for https://github.com/flutter/flutter/issues/32792
> Fix Windows project for paths with spaces

- plugins/README.md
- plugins/example_plugin/windows/.gitignore
- plugins/example_plugin/windows/ExamplePlugin.vcxproj
- plugins/example_plugin/windows/ExamplePlugin.vcxproj.filters
- plugins/example_plugin/windows/ExamplePlugin.vcxproj.user
- plugins/example_plugin/windows/example_plugin.cpp
- plugins/example_plugin/windows/example_plugin.h
- plugins/example_plugin/windows/scripts/cache_flutter.bat
- testbed/lib/main.dart
- testbed/windows/Runner.sln
- testbed/windows/Runner.vcxproj
- testbed/windows/scripts/bundle_assets_and_deps.bat
- testbed/windows/testbed.cpp
Adds an example_plugin implementation for Windows.
As with other platforms, the current build approach is a placeholder
which will be replaced with real dependency management in the future.
For now, the structure is that the plugin project is designed to only be
buildable from a Runner.sln; it uses Generated.props from the
Runner's source directory, and it builds into the Runner's build
directory.
As with the other platforms, this does not have dependencies on the rest
of FDE, should should be copyable as a starting point for making other
experimental plugins on Windows.
Also updates the plugin README to reflect that Windows now has an
example, and does some minor cleanup (e.g., standardizing example
code on using the example plugin).
Fixes #357
> Implement example_plugin for Windows

- plugins/color_panel/LICENSE
- plugins/color_panel/pubspec.yaml
- plugins/example_plugin/LICENSE
- plugins/example_plugin/analysis_options.yaml
- plugins/example_plugin/pubspec.yaml
- plugins/file_chooser/LICENSE
- plugins/file_chooser/pubspec.yaml
- plugins/menubar/LICENSE
- plugins/menubar/pubspec.yaml
- plugins/window_size/LICENSE
- plugins/window_size/pubspec.yaml
In preparation for proper plugin tooling on desktop, makes all of the
plugins look more like standard plugin packages:
- Actually marks them as Flutter plugins in pubspec.yaml
- Adds proper descriptions, author info, etc. in pubspec.yaml
- Adds directory-level LICENSE files.
- Removes analysis_options.yaml from example_plugin, since
example_plugin is designed to be copied, but that file has a relative
path.
Doesn't change anything about how plugins are actually consumed on any
platform, but does cause the flutter tool to recognize them as plugins
(e.g., creates .flutter-plugins during package fetching).
> Configure plugins as plugin packages

- example/macos/PluginRegistrant.h
- example/macos/PluginRegistrant.m
- plugins/color_panel/macos/FLEColorPanelPlugin.h
- plugins/color_panel/macos/FLEColorPanelPlugin.mm
- plugins/example_plugin/macos/Classes/FDEExamplePlugin.h
- plugins/example_plugin/macos/Classes/FDEExamplePlugin.m
- plugins/file_chooser/macos/FLEFileChooserPlugin.h
- plugins/file_chooser/macos/FLEFileChooserPlugin.mm
- plugins/menubar/macos/FLEMenubarPlugin.h
- plugins/menubar/macos/FLEMenubarPlugin.mm
- plugins/window_size/macos/FLEWindowSizePlugin.h
- plugins/window_size/macos/FLEWindowSizePlugin.mm
- testbed/macos/PluginRegistrant.h
- testbed/macos/PluginRegistrant.m
FLEPlugin* was FlutterPlugin* in https://github.com/flutter/engine/pull/9074
This updates all the runner and plugin code for that change.
> Update macOS code for the plugin API rename

- example/windows/scripts/prepare_dependencies.bat
- testbed/windows/scripts/prepare_dependencies.bat
The call was missing quoting, which will be an issue if FLUTTER_ROOT
contains spaces.
Fixes #415
> Quote call to tool_backend in Windows build

- .travis.yml
Recent Flutter changes require a newer version of CocoaPods than is
pre-installed.
> Install newer CocoaPods in CI

- plugins/menubar/lib/src/menu_channel.dart
- plugins/menubar/lib/src/menu_item.dart
- plugins/menubar/macos/Classes/MenubarPlugin.m
- testbed/lib/main.dart
Adds the ability to set shortcuts for menu items, using the same format
on the Dart side that will be used for Action shorcuts. Currently only
the macOS platform implementation uses them.
There are some limitations around non-ascii keys, which will be resolved
via a full generated keymap once this is folded into Flutter, but common
cases are special-cased, and more special-casing can be added as needed
by clients.
Adds various shortcuts to the testbed app, exercising various modifiers
and special cases.
Partially addresses #95
> Add initial shortcut support to menubar for macOS

- plugins/example_plugin/macos/Classes/ExamplePlugin.m
- plugins/example_plugin/macos/Classes/SwiftExamplePlugin.swift
- plugins/example_plugin/macos/example_plugin.podspec
- testbed/macos/Podfile
- testbed/macos/Podfile.lock
- testbed/macos/Runner.xcodeproj/project.pbxproj
Uses the same structure as an iOS Flutter plugin using the Swift
template, with an ObjC interface wrapper.
This required adding use_frameworks to the Podfile, which will be added
to the template upstream as well.
Also adds the disable_input_output_paths that was added upstream to
address strict build issues with duplicate outputs.
Fixes #421
> Convert macOS example_plugin to Swift

- testbed/lib/keyboard_test_page.dart
Re-adds the accidentally removed handling of Android key events, which
the Windows and Linux shells still send.
Fixes #323
> Fix key event test page for Windows and Linux

- plugins/flutter_plugins/shared_preferences_fde/.gitignore
- plugins/flutter_plugins/shared_preferences_fde/LICENSE
- plugins/flutter_plugins/shared_preferences_fde/macos/Classes/SharedPreferencesPlugin.swift
- plugins/flutter_plugins/shared_preferences_fde/macos/shared_preferences_fde.podspec
- plugins/flutter_plugins/shared_preferences_fde/pubspec.yaml
- testbed/lib/main.dart
- testbed/macos/Flutter/GeneratedPluginRegistrant.swift
- testbed/macos/Podfile.lock
- testbed/pubspec.yaml
Implements shared_preferences_fde for macOS, for use with the
flutter/plugins shared_preferences plugin.
This is the macOS portion of #434
> Add shared_preferences implementation for macOS

- testbed/lib/main.dart
Makes two changes to testbed for testing scrolling behavior:
- Adds a scrollable list.
- Wraps the whole application in a vertical scroll box, to allow easy
testing of nested scrolling. (Also improves behavior when window
is too small for the entire contents.)
Fixes #364
> Add scrolling test to testbed

- example/macos/Base.lproj/MainMenu.xib
- example/macos/ExampleWindow.swift
- testbed/macos/Base.lproj/MainMenu.xib
- testbed/macos/FlutterWindow.swift
Updates example and testbed for the breaking change in
https://github.com/flutter/engine/pull/9741
Removes FLEViewController and FLEView from the XIBs,
and instead adds the view controllers in code (which now
internally manages the view).
Fixes #10
> Update FLEViewController creation

- example/macos/ExampleWindow.swift
- testbed/macos/FlutterWindow.swift
Updates macOS Runners for
flutter/engine#9750
Projects are now configured via init, and there is no explicit launch
command on a view controller.
> Remove launch call on FLEViewController

- plugins/flutter_plugins/url_launcher_fde/linux/url_launcher_fde_plugin.cc
Adds a missing return in error handling, leading to a path that calls
|result| twice.
Also fixes a comment that was left over from an earlier plugin that kept
a channel reference.
> Fix double-result on error in Linux url_launcher

- .appveyor.yml
- .travis.yml
Although building the applications in release mode still uses debug Flutter
libraries on all frameworks, adding a release build ensures that we have
coverage on the runner-specific aspects of building in release mode.
It will also be useful as release libraries become available, to ensure that
we have coverage for changes for that on the Flutter side.
> Add release builds to CI

- example/.gitignore
- testbed/.gitignore
Build output for macOS is now under .dart_tool, not build, so update the
ignored directories to include that.
> Update gitignore for build output changes

- example/macos/Runner.xcodeproj/project.pbxproj
- testbed/macos/Runner.xcodeproj/project.pbxproj
as discussed in https://github.com/flutter/flutter/issues/38863, these won't work with multiple configurations - though the flutter_tool driven caching will still apply so the loss isn't huge.
> Remove xcfilelist input and outputs

- example/lib/main.dart
- testbed/lib/keyboard_test_page.dart
Depends on https://github.com/flutter/engine/pull/9386
> [glfw] Use RawKeyEventDataLinux on testbed keyboard page

- testbed/lib/main.dart
Accessing the window_size plugin before running the app triggers a new
assertion; this ensures that the relevant component is initialized (per
the instructions in the assertion message).
> Fix new assertion in Testbed

- example/macos/Runner.xcodeproj/project.pbxproj
- testbed/macos/Runner.xcodeproj/project.pbxproj
https://github.com/flutter/engine/pull/11380 adds support for looking up
flutter_assets from App.framework, which the 'flutter' tool packages, so
we no longer need to copy them into the main bundle.
Also does some minor project cleanup around the addition of
App.framework to make it consisent with FlutterMacOS (moved to Flutter
rather than Frameworks, and removes an accidental addition of a
reference to the on-disk Flutter folder in 'example').
> Stop copying flutter_assets to the main bundle

- plugins/file_chooser/android/build.gradle
- plugins/file_chooser/android/src/main/AndroidManifest.xml
in #440 you mention to be open for adding dummy modules for android&ios to enable mobile compilation.. this adds an empty android module for file_chooser, just to make gradle happy.
If you like I can add it also to the other plugins (it would only require customizing the package name in `AndroidManifest.xml` for each plugin i guess). Although i'm not sure if dummy plugins will be made obsolete by https://github.com/flutter/flutter/pull/38632 ?
> dummy android module for file_chooser plugin

- plugins/flutter_plugins/path_provider_fde/.gitignore
- plugins/flutter_plugins/path_provider_fde/LICENSE
- plugins/flutter_plugins/path_provider_fde/macos/Classes/PathProviderPlugin.swift
- plugins/flutter_plugins/path_provider_fde/macos/path_provider_fde.podspec
- plugins/flutter_plugins/path_provider_fde/pubspec.yaml
- testbed/lib/main.dart
- testbed/macos/Flutter/GeneratedPluginRegistrant.swift
- testbed/macos/Podfile.lock
- testbed/pubspec.yaml
Implements path_provider_fde for macOS, for use with the
flutter/plugins path_provider plugin.
Doesn't currently implement the method for accessing the storage root
since there's not a final decision yet on whether to sandbox by default.
> Add path_provider implementation for macOS

- plugins/example_plugin/windows/ExamplePlugin.vcxproj
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj
Currently for only existed implementations of windows side plugins
PS:
i don't change the characterset on properties file i see that example solution file uses multibyte https://github.com/google/flutter-desktop-embedding/blob/master/example/windows/Runner.vcxproj#L25
but example_plugin uses unicode characterset is this change forgotten ?
> Added Multiple Solution Targets for VS proj file

- plugins/example_plugin/windows/ExamplePlugin.vcxproj
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj
This reduces the number of changes necessary for enabling CRL in a
plugin, and having C++ exceptions enabled isn't necessarily desirable
anyway.
Applies the same change to url_launcher_fde since with some few plugins
at the moment, people may use that as a template instead.
> Disable C++ exceptions in example plugin

- plugins/flutter_plugins/path_provider_fde/pubspec.yaml
The PR adding this plugin was posted before the change to pubspec.yaml
but landed after, so it doesn't work with the current version of
Flutter.
> Switch plugin declaration for path_provider_fde

- example/windows/AppConfiguration.props
- example/windows/Runner.vcxproj
- example/windows/Runner.vcxproj.filters
- example/windows/main.cpp
- example/windows/window_configuration.cpp
- example/windows/window_configuration.h
- testbed/windows/AppConfiguration.props
- testbed/windows/Runner.vcxproj
- testbed/windows/Runner.vcxproj.filters
- testbed/windows/main.cpp
- testbed/windows/window_configuration.cpp
- testbed/windows/window_configuration.h
Rather than having the Window title and size be inlined in main.cpp,
where local modifications will cause conflicts on every API update,
move them to a separate constants file. This will help isolate early
users of the Windows embedding from API churn as we iterate on the
Windows Flutter API surface.
Per the comment in the file this is not a long-term solution to
configuration, but it should help in the short term.
Also moves the executable name out of the project and into
a .props file, to similarly simplify maintain a local edit of that
likely change.
> Move Windows window setup and exe name to configs

- example/App-Customization.md
- example/README.md
As example/ continues to evolve into a template, it's useful to capture
what is necessary to change core metadata like the application name.
Fixes #545
> Add initial customization documentation

- example/windows/.gitignore
- example/windows/Runner.vcxproj
- example/windows/Runner.vcxproj.filters
- plugins/example_plugin/windows/ExamplePlugin.vcxproj
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj
- testbed/windows/.gitignore
- testbed/windows/Runner.vcxproj
- testbed/windows/Runner.vcxproj.filters
Updates the Windows builds for the breaking change in
https://github.com/flutter/flutter/pull/40194
Note: plugins continue to hard-code the cache dir instead of using
FLUTTER_EPHEMERAL_DIR since currently they share the generated
properties file, but need a project-local copy of the cache. That
whole structure needs to be reworked, so the fact that it's
currently hard-coded isn't worth trying to fix right now
(e.g., by making FLUTTER_EPHEMERAL_DIR relative).
> Update Windows project for ephemeral dir

- example/pubspec.yaml
- testbed/pubspec.yaml
This should have been done as part of #553; it would have avoided #556.
Since there have been several other recent desktop-related fixes, this
requires a new enough version to pick them up as well to reduce the
chance of people hitting them.
> Roll minimum Flutter version forward

- example/windows/FlutterBuild.vcxproj
- testbed/windows/FlutterBuild.vcxproj
Even though FlutterBuild.vcxproj doesn't actually use the C++ toolchain,
VS checks it as part of the build process, so listing only 141 prevents
building in a VS 2019 install that only has v142 (the default).
Fixes https://github.com/flutter/flutter/issues/40532
> Apply the toolchain branching to FlutterBuild

- example/windows/win32_window.cc
- testbed/windows/win32_window.cc
This will requires https://github.com/flutter/engine/pull/12276/files for the new embedding api
> added windows system fonts listener

- plugins/file_chooser/android/build.gradle
- plugins/file_chooser/android/src/main/AndroidManifest.xml
- plugins/flutter_plugins/connectivity_fde/pubspec.yaml
- plugins/flutter_plugins/path_provider_fde/android/build.gradle
- plugins/flutter_plugins/path_provider_fde/android/src/main/AndroidManifest.xml
- plugins/flutter_plugins/url_launcher_fde/android/build.gradle
- plugins/flutter_plugins/url_launcher_fde/android/src/main/AndroidManifest.xml
As of https://github.com/flutter/flutter/pull/40640 these should no
longer be necessary.
Also fixes a typo in a plugin pubspec.yaml.
> Remove dummy Android implementations of plugins

- example/windows/FlutterBuild.vcxproj
- testbed/windows/FlutterBuild.vcxproj
Even though the SDK isn't used by this project, VS still appears to do
SDK validation when the build starts (as with the tool version).
Longer term, the ideal solution would be to find a project template that
doesn't require setting tool and SDK versions that we don't need, if
possible, since all it needs to do is run a script.
Fixes #592
> [windows] Add SDK to FlutterBuild

- .appveyor.yml
- .travis.yml
The CI scripts were never updated to use the new 'flutter config'
workflow, and are instead relying on the environment variable fallback.
This switches to the new workflow for both Travis and AppVeyor.
> Switch CI to use 'flutter config'

- .appveyor.yml
Also removes the VS tools from the PATH, since that should no longer be necessary with current Flutter tooling.
> Switch Windows CI to VS 2019

- example/linux/flutter/generated_plugin_registrant.cc
`flutter build linux` was giving this error:
```
flutter/generated_plugin_registrant.cc:5:10: fatal error: 'plugin_registrant.h' file not found
#include "plugin_registrant.h"
```
> {linux}/generated_plugin_registrant.cc: [fix] #include wrong filename

- plugins/file_chooser/macos/Classes/FLEFileChooserPlugin.m
The registrar is not guaranteed to have a view at registration time, and
in practice no longer does causing file_chooser to have a nil view. It
should instead be storing the registrar, and getting the view on demand.
Fixes #633
> File file_chooser macOS view reference

- plugins/file_chooser/.gitignore
- plugins/file_chooser/pubspec.yaml
- plugins/file_chooser/windows/.gitignore
- plugins/file_chooser/windows/PluginInfo.props
- plugins/file_chooser/windows/file_chooser.vcxproj
- plugins/file_chooser/windows/file_chooser.vcxproj.filters
- plugins/file_chooser/windows/file_chooser_plugin.cpp
- plugins/file_chooser/windows/file_chooser_plugin.h
- testbed/windows/FlutterPlugins.props
- testbed/windows/Runner.sln
- testbed/windows/flutter/generated_plugin_registrant.cc
> Implement file_chooser for Windows

- example/windows/main.cpp
- plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.cpp
`codecvt_utf8` is for UCS2, not UTF-16, and all versions of Windows we would
conceivably support use UTF-16. This replaces the incorrect conversions with the
correct `codecvt_utf8_utf16`.
> Fix wide-to-utf8 conversions on Windows

- plugins/file_chooser/windows/file_chooser.vcxproj
- plugins/flutter_plugins/path_provider_fde/windows/path_provider_fde.vcxproj
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj
- plugins/sample/windows/sample.vcxproj
- plugins/window_size/windows/window_size.vcxproj
- testbed/windows/FlutterPlugins.props
Giving them a suffix makes it easier to identify what the DLL is. This is also consistent with the current naming for Linux plugins.
(Longer term the name may be controlled via a pubspec key or similar instead of being expected to follow a set form, but for now this is potentially useful.)
> Add a _plugin suffix to plugin DLLs

- plugins/file_chooser/lib/file_chooser.dart
- plugins/file_chooser/lib/src/channel_controller.dart
- plugins/file_chooser/lib/src/filter_group.dart
- plugins/file_chooser/lib/src/utilities.dart
- plugins/file_chooser/linux/file_chooser_plugin.cc
- plugins/file_chooser/macos/Classes/FLEFileChooserPlugin.m
- plugins/file_chooser/windows/file_chooser_plugin.cpp
- testbed/lib/main.dart
- testbed/macos/Podfile.lock
Allows for more functionality in file chooser filtering on Windows and Linux,
by allowing the specification of filter groups rather than just a flat list of
extensions.
Fixes #650
> Allow filter groups in file_chooser

- example/windows/Runner.vcxproj
- example/windows/main.cpp
- example/windows/win32_window.cc
- example/windows/win32_window.h
- plugins/file_chooser/windows/file_chooser.vcxproj
- plugins/file_chooser/windows/file_chooser_plugin.cpp
- plugins/flutter_plugins/path_provider_fde/windows/path_provider_fde.vcxproj
- plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.cpp
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_plugin.cpp
- plugins/sample/README.md
- plugins/sample/windows/sample.vcxproj
- plugins/window_size/windows/window_size.vcxproj
- plugins/window_size/windows/window_size_plugin.cpp
- testbed/windows/Runner.vcxproj
- testbed/windows/main.cpp
- testbed/windows/win32_window.cc
- testbed/windows/win32_window.h
This is a complete pass over all the code and projects, making a variety of changes:
- Updating style to better match Google style for Windows code (e.g., avoiding LP* types)
- Increasing the warning level for everything from W3 to W4
- Enabling warnings as errors (WX)
- Fixing all warnings
- Including correctly disabling exceptions in STL via a Define
- clang-formatted some missed files
Fixes #662 
Fixes #582 
Addresses Windows portion of #343
> Misc. Windows code cleanup

- example/linux/Makefile
- plugins/README.md
- plugins/flutter_plugins/url_launcher_fde/linux/Makefile
- testbed/linux/Makefile
- testbed/windows/Runner.sln
Switches Windows and Linux to using the new plugin symlinks. This eliminates
the need for project files/makefiles to have developer-specific paths
(especially if pulled via pub).
Now that the plugin plumbing is mostly generic for Linux, most of it in moved
into the example Makefile so that the changes necessary to use plugins are
much more targeted. Updates the documentation for using plugins on Linux
to be more specific now that the process is more straightforward.
Part of #578
> Use plugin symlinks on Windows and Linux

- example/windows/win32_window.cc
- testbed/windows/win32_window.cc
This was causing crashes on Win 7 since that function is not available.
> Check for null on EnableNonClientDpiScaling

- plugins/README.md
- testbed/windows/Runner.sln
Regenerates the testbed solution's plugin integration using
https://github.com/flutter/flutter/pull/51246. Other than adding the
Flutter Plugins folder, it just ends up reordering some of the
entries.
> Regenerate testbed solution from tool

- example/lib/main.dart
- testbed/lib/main.dart
Changes the platform override to better match current platforms:
- Don't override for macOS, now that it's supported.
- Make the check more targeted, so that it shows an override
approach that would work in project including mobile and/or web.
> Update platform override

- example/README.md
- example/lib/main.dart
- testbed/lib/main.dart
Now that Linux and Windows are supported by TargetPlatform, remove the
override.
Also fixes a few minor new analyzer issues in the main.dart files.
> Remove TargetPlatform overrides

- testbed/gtk/Makefile
- testbed/gtk/main.cc
Currently requires building the normal Linux runner with a local engine
first, then piggy-backs on the resources set up by that build.
> Very initial prototype of a GTK runner

- testbed/lib/keyboard_test_page.dart
Now that https://github.com/flutter/flutter/issues/37710 has landed, we can listen to Windows keys
> Adds RawKeyEventDataWindows to Testbed

- plugins/color_panel/pubspec.yaml
- plugins/file_chooser/pubspec.yaml
- plugins/flutter_plugins/path_provider_fde/pubspec.yaml
- plugins/flutter_plugins/url_launcher_fde/pubspec.yaml
- plugins/menubar/pubspec.yaml
- plugins/window_size/pubspec.yaml
- testbed/lib/main.dart
- testbed/pubspec.yaml
- testbed/test/widget_test.dart
Plugins from FDE should not be published. Add a hurdle so that anyone
who thinks doing so is a good idea, against the explicit guidance of
both this project and the Flutter for desktop documentation, has to go out
of their way to do so.
Also removes the deprecated author, and the homepage (since no published
plugin should ever be linking here).
> Adjust plugin metadata

- plugins/color_panel/linux/CMakeLists.txt
- plugins/file_chooser/linux/CMakeLists.txt
- plugins/flutter_plugins/url_launcher_fde/linux/CMakeLists.txt
- plugins/menubar/linux/CMakeLists.txt
- plugins/window_size/linux/CMakeLists.txt
- testbed/linux/CMakeLists.txt
- testbed/linux/flutter/CMakeLists.txt
The linux template build files were updated to use hidden as the default
visibity. This updates all plugins, and testbed, to match.
Fixes undefined behavior in testbed (commonly, crash on launch) on Linux
due to unintended sharing of the plugin manager across plugins.
> Update Linux plugin build for template changes

- plugins/color_panel/lib/color_panel.dart
Picking a color like #bf4040 would result in Flutter using the color #bf3f3f.
> Fix rounding in color plugin.

- testbed/gtk/CMakeLists.txt
- testbed/gtk/fl_application.cc
- testbed/gtk/fl_application.h
- testbed/gtk/main.cc
This fixes a compile warning about an unused FL_IS_APPLICATION.
Fixes #759
> Split FlApplication into its own module.

- plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.cpp
The path_provider_plugin for Windows is still in the FDE repository but works well.
But it misses the `getDownloadsPath` call on Windows which is available for macOS.
This PR fixes this.
> path_provider in FDE now supports getDownloadsPath on windows

- testbed/lib/main.dart
- testbed/pubspec.yaml
Now that shared_preferences supports Linux, add it to the existing prefs
usage in testbed.
> Use shared_preferences on Linux

- plugins/flutter_plugins/url_launcher_fde/README.md
- plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_plugin.cpp
- testbed/lib/main.dart
Checks the registry for a url protocol entry for the given scheme when
checking to see if a URL can be launched.
This gives better parity with the other platforms, and means that the
url_launcher-documentation-recommended pattern of checking canLaunch
before calling launch won't fail on Windows.
> Add canLaunch to Windows url_launcher

- .github/workflows/ci.yml
There have been changes to GitHub actions that break new CI runs; this updates setting the path to fix that (and updates the macOS version to fix a warning)
> Update CI script

- plugins/file_chooser/windows/file_chooser_plugin.cpp
The docs for the relevant interfaces say they are in _core.h, but
to include the non-_core header.
> Update shobjidl include

- testbed/macos/Podfile
- testbed/macos/Podfile.lock
- testbed/macos/Runner.xcodeproj/project.pbxproj
This is the result of removing macos/Podfile and then rebuilding with the current Flutter master, which includes a project migration.
> Update testbed for macOS project migration

- plugins/window_size/lib/src/window_size_channel.dart
- plugins/window_size/lib/src/window_size_utils.dart
- plugins/window_size/linux/window_size_plugin.cc
- plugins/window_size/macos/Classes/FLEWindowSizePlugin.m
- plugins/window_size/windows/window_size_plugin.cpp
Adds 'setWindowVisibility' to show/hide the window.
Needs follow-up documentation; using it correctly for the resize-before-showing-window case is non-trivial on some platforms, and on macOS hiding will exit the app with the default Flutter app delegate configuration.
> [window_size] Add show/hide functionality

- plugins/file_selector/README.md
- plugins/file_selector/file_selector_linux/CHANGELOG.md
- plugins/file_selector/file_selector_linux/README.md
- plugins/file_selector/file_selector_linux/pubspec.yaml
- plugins/file_selector/file_selector_macos/CHANGELOG.md
- plugins/file_selector/file_selector_macos/README.md
- plugins/file_selector/file_selector_macos/pubspec.yaml
- plugins/file_selector/file_selector_windows/CHANGELOG.md
- plugins/file_selector/file_selector_windows/README.md
- plugins/file_selector/file_selector_windows/pubspec.yaml
Rev the SDK constraint on the file_selector implementation packages to
indicate compatibility with null safety. No code changes necessary,
since there is no Dart code.
> Update file_selector SDK constraints

- plugins/file_selector/file_selector_macos/CHANGELOG.md
- plugins/file_selector/file_selector_macos/README.md
- plugins/file_selector/file_selector_macos/pubspec.yaml
Removes duplicated text in file_selector_macos README.
> Fix copypasta in README

- plugins/file_selector/file_selector_linux/pubspec.yaml
- plugins/file_selector/file_selector_macos/pubspec.yaml
- plugins/file_selector/file_selector_windows/pubspec.yaml
Recent versions of Flutter warn if this key isn't present.
> Add implements to file_selector_*

- plugins/file_selector/example/analysis_options.yaml
- plugins/file_selector/example/lib/get_directory_page.dart
- plugins/file_selector/example/lib/home_page.dart
- plugins/file_selector/example/lib/open_image_page.dart
- plugins/file_selector/example/lib/open_multiple_images_page.dart
- plugins/file_selector/example/lib/open_text_page.dart
- plugins/file_selector/example/lib/save_text_page.dart
- plugins/file_selector/example/pubspec.lock
- plugins/file_selector/example/pubspec.yaml
Just to make absoulety sure that there are no issues with the platform
implementations for NNBD (e.g., bad dependency versions).
Also tidies up the example for this repo's analysis_options.yaml, since
it was written against flutter/plugins originally which has different
settings, as well as replacing some deprecated material buttons.
> Migrate file selector example to NNBD

- plugins/file_selector/file_selector_macos/macos/Classes/FLEFileSelectorPlugin.m
The null safety migration for file_selector defaults the accept group to
an empty set rather than null, so empty set needs to be treated as no
filter. That's already the case for Windows and Linux; this makes macOS
consistent with that.
> [file_selector] Ignore empty accept group lists on macOS

- plugins/window_size/linux/window_size_plugin.cc
The GTK default is (-1, -1), which looks like Size(-1, -1) to Flutter.
GTK uses -1 for requisition size (the size GTK has calculated), so we map that to (0, 0).
> [window_size] Fix getWindowMinSize in Linux

- plugins/file_selector/example/lib/open_image_page.dart
- plugins/file_selector/example/lib/open_multiple_images_page.dart
- plugins/file_selector/example/lib/open_text_page.dart
- plugins/file_selector/example/lib/save_text_page.dart
- plugins/file_selector/example/pubspec.lock
- plugins/file_selector/example/windows/flutter/CMakeLists.txt
- Add suggested filename to save dialog (this was a bug in the example,
which was copied from file_selector, whose examples were written on web
where that is a no-op, so was missed).
- Update dependencies, and update null handling as a result of the fix
that was recently made to cross-file.
Fixes #849
> [file_selector] Minor updates to example app

- plugins/menubar/lib/src/menu_channel.dart
Fix alphabetical key shortcuts. A SHIFT modifier key was registered by accident since the keyLabel from a LogicalKeyboardKey in Flutter changed to an upper case value
Fixes https://github.com/google/flutter-desktop-embedding/issues/865
> Fix alphabetical key shortcuts.

- plugins/file_selector/example/linux/flutter/CMakeLists.txt
Updates to match https://github.com/flutter/flutter/pull/78415
Avoids having a dependency that `doctor` no longer flags as necessary.
Fixes https://github.com/google/flutter-desktop-embedding/issues/867
> Remove unneeded libraries from Linux example

- plugins/file_selector/example/README.md
- plugins/file_selector/file_selector_linux/CHANGELOG.md
- plugins/file_selector/file_selector_linux/README.md
- plugins/file_selector/file_selector_linux/pubspec.yaml
- plugins/file_selector/file_selector_macos/CHANGELOG.md
- plugins/file_selector/file_selector_macos/README.md
- plugins/file_selector/file_selector_macos/pubspec.yaml
- plugins/file_selector/file_selector_windows/CHANGELOG.md
- plugins/file_selector/file_selector_windows/README.md
- plugins/file_selector/file_selector_windows/pubspec.yaml
Link to pub.dev installation instructions instead of showing an example, to make the instructions evergreen.
> [file_selector] Update install instructions

- plugins/file_selector/file_selector_linux/pubspec.yaml
- plugins/file_selector/file_selector_macos/pubspec.yaml
- plugins/file_selector/file_selector_windows/pubspec.yaml
NNBD no longer requires a prerelease constraint. Fixes a publish
warning.
> [file_selector] Make SDK constraint non-prerelease

- plugins/window_size/linux/window_size_plugin.cc
Hello everyone!
Nice plugin!
But in our gitlab CI the build failed with following error message:
```
/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:345:7: error: use of undeclared identifier 'strcmp'
/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:347:14: error: use of undeclared identifier 'strcmp'
/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:349:14: error: use of undeclared identifier 'strcmp'
/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:351:14: error: use of undeclared identifier 'strcmp'
/linux/flutter/ephemeral/.plugin_symlinks/window_size/linux/window_size_plugin.cc:353:14: error: use of undeclared identifier 'strcmp' …
```
> [window_size] Include cstring
