macos/library/update_engine.sh
Cleanup to better follow Google style guide for bash scripts.
=> Style fixes for update_engine.sh

linux/library/flutter_embedder.cc
Wrote in the wrong params for glClearColor.  They are now correct (the
value for colors is 0.1 not 0-255).
=> [linux] Actually clear to blue grey.

linux/Makefile
Handles an issue brought up in #31
=> Fix makefile deps to prevent parallelized building.

linux/library/src/flutter_embedder.cc
The `jsoncpp` [Reader](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_reader.html) and [FastWriter](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/class_json_1_1_fast_writer.html) classes are [depreacted](http://open-source-parsers.github.io/jsoncpp-docs/doxygen/deprecated.html).
Because of this `flutter-desktop-embedding` fails to compile using `jsoncpp`-`v1.8.4` on ArchLinux.
This PR attempts to fix this by using the newer `jsoncpp` API.
PS: Please review this carefully because I don't know `C` and I'm unable to run this code in order to test it. It does seem to compile though.
=> [linux] Fix jsoncpp deprecations

windows/README.md
The configuration names were changed from .dll and .lib to Dynamic Library and Static Library which changed the output directory.
=> Update README Run Example

library/windows/GLFW Library.vcxproj, library/windows/GLFW Library.vcxproj.filters, library/windows/embedder.cpp
Enables the GLFW raw key event handler for Windows.
=> [windows] Add key event support

library/common/glfw/flutter_window_controller.cc
=> Fix array-out-of-bounds

library/common/client_wrapper/include/flutter_desktop_embedding/glfw/flutter_window_controller.h, library/common/client_wrapper/src/glfw/flutter_window_controller.cc, library/common/glfw/embedder.cc, library/include/flutter_desktop_embedding_core/glfw/embedder.h
Fixes some minor warnings that show up in the Windows build.
=> Warning fixes

README.md, tools/dart_tools/bin/doctor.dart
This should slightly simplify the process of figuring out if people have
missed a setup step when getting started with the project.
=> Add a simple dependency checking script

library/common/client_wrapper/include/flutter_desktop_embedding/glfw/flutter_window_controller.h, library/common/client_wrapper/src/glfw/flutter_window_controller.cc, library/common/glfw/embedder.cc, library/include/flutter_desktop_embedding_core/glfw/embedder.h
Adds an option to enable mouse tracking to send hover events to the
Flutter engine.
Fixes #92
=> [glfw] Add hover support

example/linux/build.sh, example/linux/name_output.sh, example/windows/build.bat, example/windows/find_vcvars.dart, example/windows/name_output.bat
Add the scripts to ennable the experimental 'flutter build' and (once available)
'flutter run' support for Windows and Linux.
=> Add build and run support for Windows and Linux

example/macos/Runner.xcodeproj/project.pbxproj, testbed/macos/Runner.xcodeproj/project.pbxproj
Moves framework sync and local engine flags into tool in https://github.com/flutter/flutter/pull/31515
=> Remove need for separate asset script

plugins/common/BUILD.gn, plugins/common/flutter_library.gni, plugins/window_size/BUILD.gn, plugins/window_size/lib/src/window_size_channel.dart, plugins/window_size/linux/include/window_size/window_size_plugin.h, plugins/window_size/linux/src/window_size_plugin.cc, plugins/window_size/macos/FLEWindowSizePlugin.mm, testbed/lib/main.dart, testbed/linux/Makefile, testbed/linux/testbed.cc, tools/dart_tools/lib/flutter_utils.dart
Adds a Linux implementation of the window resize plugin using the new
APIs in the library.
Fixes #99
=> Implement window resize plugin for Linux

testbed/linux/.gitignore
This was intended to be part of #375, but was accidentally omitted.
=> Add .gitignore for testbed/linux/

example/macos/ExampleWindow.swift, testbed/macos/FlutterWindow.swift
Update for compatibilty with API change in
https://github.com/flutter/engine/pull/9672
=> Update macOS projects for switch to FLEDartProject

plugins/window_size/macos/Classes/FLEWindowSizePlugin.m
Fixes the bug were registrar.view is nil at plugin creation time caused by recent updates to FLEViewController.
=> [macos] Hold a reference to registrar in WindowSizePlugin

example/macos/Runner.xcodeproj/project.pbxproj, testbed/macos/Runner.xcodeproj/project.pbxproj
Reverts google/flutter-desktop-embedding#459
=> Revert "Updates to Xcode project to support flutter assemble"

example/macos/ExampleWindow.swift, testbed/macos/FlutterWindow.swift
Updates examples for https://github.com/flutter/engine/pull/11010
=> Update for FLE->Flutter switch

example/macos/Runner.xcodeproj/project.pbxproj, testbed/macos/Runner.xcodeproj/project.pbxproj
Requires https://github.com/flutter/flutter/pull/37425
Adds an App.framework and places assets under this framework. This project can be transparently updated to support release/profile once the artifacts are available.
=> Update projects to include App.framework for release mode

example/linux/Makefile, example/windows/Runner.vcxproj, example/windows/Runner.vcxproj.filters, example/windows/scripts/bundle_assets_and_deps.bat, plugins/color_panel/linux/Makefile, plugins/example_plugin/linux/Makefile, plugins/example_plugin/windows/ExamplePlugin.vcxproj, plugins/example_plugin/windows/ExamplePlugin.vcxproj.filters, plugins/file_chooser/linux/Makefile, plugins/flutter_plugins/url_launcher_fde/linux/Makefile, plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj, plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_fde.vcxproj.filters, plugins/menubar/linux/Makefile, plugins/window_size/linux/Makefile, testbed/linux/Makefile, testbed/windows/Runner.vcxproj, testbed/windows/Runner.vcxproj.filters, testbed/windows/scripts/bundle_assets_and_deps.bat
Updates Windows and Linux for https://github.com/flutter/flutter/pull/38858
Part of https://github.com/flutter/flutter/issues/38589
=> Update library/wrapper names on Windows and Linux

example/macos/Runner.xcodeproj/project.pbxproj, testbed/macos/Runner.xcodeproj/project.pbxproj
Place the flutter_assets under the Resources directory. 
Requires https://github.com/flutter/flutter/pull/38748
=> Correct flutter_assets path for full framework

example/linux/flutter_embedder_example.cc, example/windows/flutter_embedder_example.cpp, testbed/linux/testbed.cc, testbed/windows/testbed.cpp
Updates the example and testbed code for the API change in
https://github.com/flutter/engine/pull/11386
=> Update GLFW CreateWindow calls

example/windows/Runner.vcxproj, example/windows/flutter_embedder_example.cpp, testbed/windows/Runner.vcxproj, testbed/windows/testbed.cpp
issuse: https://github.com/flutter/flutter/issues/31268
Specify the link options in both modes explicitly, adapting different codes for different options.
=> bugfix: #31268

example/pubspec.yaml, plugins/color_panel/pubspec.yaml, plugins/example_plugin/pubspec.yaml, plugins/file_chooser/pubspec.yaml, plugins/flutter_plugins/shared_preferences_fde/pubspec.yaml, plugins/flutter_plugins/url_launcher_fde/pubspec.yaml, plugins/menubar/pubspec.yaml, plugins/window_size/pubspec.yaml, testbed/macos/Podfile, testbed/pubspec.yaml
Updates all plugins to conform to the new plugin schema in
https://github.com/flutter/flutter/pull/38632
=> Update plugins for platform yaml changes

plugins/example_plugin/macos/Classes/ExamplePlugin.swift, plugins/flutter_plugins/shared_preferences_fde/macos/Classes/SharedPreferencesPlugin.swift, plugins/flutter_plugins/url_launcher_fde/macos/Classes/UrlLauncherPlugin.swift
Also fixes a license mistake from converting a PR from flutter/plugins
to this repository; the code was mistakenly still using the boilerplate
for flutter/plugins. The LICENSE file correctly matched this repository.
Fixes #513
=> Fixes style issues in Swift plugins

example/macos/AppDelegate.swift, example/macos/MainFlutterWindow.swift, plugins/example_plugin/macos/Classes/ExamplePlugin.swift, plugins/flutter_plugins/path_provider_fde/macos/Classes/PathProviderPlugin.swift, plugins/flutter_plugins/shared_preferences_fde/macos/Classes/SharedPreferencesPlugin.swift, plugins/flutter_plugins/url_launcher_fde/macos/Classes/UrlLauncherPlugin.swift, testbed/macos/AppDelegate.swift, testbed/macos/FlutterWindow.swift
- Switches plugin method matching from if/else-if chains to switch,
which gives cleaner code.
- Applies changes from running the latest version of swift-format, with
a few manual changes where it didn't handle things well.
=> More Swift cleanup

example/linux/.gitignore, example/linux/Makefile, testbed/linux/.gitignore, testbed/linux/Makefile
Updates the build for the breaking change in
https://github.com/flutter/flutter/pull/40587
=> Update Linux for ephemeral directory

example/App-Customization.md
This is a simple PR to update the file that explains which file to change for Linux customization.
=> [Linux] Update Customization instructions in example

example/windows/main.cpp, testbed/windows/main.cpp
Updates the runners for the breaking change in
https://github.com/flutter/engine/pull/15378
=> Update Windows runners for HWND access change

plugins/flutter_plugins/path_provider_fde/.gitignore, plugins/flutter_plugins/path_provider_fde/LICENSE, plugins/flutter_plugins/path_provider_fde/README.md, plugins/flutter_plugins/path_provider_fde/ios/path_provider_fde.podspec, plugins/flutter_plugins/path_provider_fde/pubspec.yaml, plugins/flutter_plugins/path_provider_fde/windows/.gitignore, plugins/flutter_plugins/path_provider_fde/windows/PluginInfo.props, plugins/flutter_plugins/path_provider_fde/windows/path_provider_fde.vcxproj, plugins/flutter_plugins/path_provider_fde/windows/path_provider_fde.vcxproj.filters, plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.cpp, plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.h, plugins/window_size/windows/flutter/generated_plugin_registrant.cc, plugins/window_size/windows/flutter/generated_plugin_registrant.h, plugins/window_size/windows/window_size.vcxproj.user, testbed/pubspec.yaml, testbed/windows/FlutterPlugins.props, testbed/windows/Runner.sln, testbed/windows/flutter/generated_plugin_registrant.cc
Adds a Windows path_provider_fde, implementing the three core methods.
Addresses #120 for Windows.
=> Basic implementation of path_provider for Windows

example/windows/runner.exe.manifest, testbed/windows/runner.exe.manifest
=> Compat `GetVersion/Ex` with Win10

plugins/flutter_plugins/url_launcher_fde/linux/url_launcher_plugin.cc
Returns true for URL schemes starting with ftp, http, and https
Fixes #706
=> Implement canLaunch for linux

testbed/linux/flutter/CMakeLists.txt
The build files have drifted apart slightly; resyncs other than
intentional changes for testbed requirements.
=> Resync Linux build with template

plugins/file_chooser/linux/file_chooser_plugin.cc
Switch to gtk_file_chooser_native, which is preferred to ensure we can utilize xdg-desktop-portals when necessary.
=> Switch to gtk_file_chooser_native

testbed/gtk/main.cc
This replaces the simplistic minimal GTK app we had before. I will also allow us to easily add a menubar.
=> Use GtkApplication

testbed/gtk/main.cc
It was changed in https://github.com/flutter/engine/pull/18809.
=> Update to use new fl_dart_project_new() API

plugins/flutter_plugins/url_launcher_fde/gtk/CMakeLists.txt, plugins/flutter_plugins/url_launcher_fde/gtk/include/url_launcher/url_launcher_plugin.h, plugins/flutter_plugins/url_launcher_fde/gtk/url_launcher_plugin.cc, testbed/gtk/flutter/gtk_plugin_registrant.cc, testbed/gtk/flutter/gtk_plugins.cmake
Part of https://github.com/flutter/flutter/issues/41721
=> Add GTK url_launcher plugin

plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_plugin.cpp, testbed/lib/main.dart
I stumbled on an exception because the url_launcher plugin is expected to return a boolean value on success. Previously the windows plugin only returned success without any value.
<details>
<summary>Otherwise an exception is thrown when await'ed</summary>
```
[+9232 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Failed assertion: boolean expression must not be null
[        ] #0      URLLauncherTestWidget.build.<anonymous closure> (package:testbed/main.dart:370:20)
[        ] <asynchronous suspension>
[        ] #1      URLLauncherTestWidget.build.<anonymous closure> (package:testbed/main.dart)
[        ] #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
[        ] #3      _InkResponseState.build.<anonymous closure> …
```
=> [url_launcher_fde] return true on success on Windows

plugins/file_chooser/windows/file_chooser_plugin.cpp, plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_plugin.cpp, plugins/window_size/windows/window_size_plugin.cpp
`EncodableValue` is now a `std::variant`; this updates all the usages of that API accordingly.
=> Update Windows plugins for EncodableValue change

plugins/menubar/.gitignore, plugins/menubar/.metadata, plugins/menubar/pubspec.yaml, plugins/menubar/windows/.gitignore, plugins/menubar/windows/CMakeLists.txt, plugins/menubar/windows/include/menubar/menubar_plugin.h, plugins/menubar/windows/menubar_plugin.cpp, testbed/lib/main.dart, testbed/windows/flutter/generated_plugin_registrant.cc, testbed/windows/flutter/generated_plugins.cmake
Implements the basic menubar plugin functionality for Windows, and
updates testbed to include it.
Does not include keyboard shortcut support.
Part of #105
=> [windows] Initial menubar implementation

plugins/file_chooser/windows/file_chooser_plugin.cpp, plugins/flutter_plugins/path_provider_fde/windows/path_provider_plugin.cpp, plugins/flutter_plugins/url_launcher_fde/windows/url_launcher_plugin.cpp, plugins/menubar/windows/menubar_plugin.cpp, plugins/window_size/windows/window_size_plugin.cpp
Uses the new default template types to avoid having to specify explicit template types everywhere.
=> Simplify Windows plugin code

analysis_options.yaml, plugins/file_chooser/lib/src/channel_controller.dart, plugins/file_chooser/lib/src/filter_group.dart, plugins/file_chooser/lib/src/result.dart, plugins/file_chooser/lib/src/utilities.dart, plugins/file_chooser/pubspec.yaml, plugins/menubar/.gitignore, plugins/menubar/lib/src/menu_channel.dart, plugins/menubar/lib/src/menu_item.dart, plugins/menubar/pubspec.yaml, plugins/window_size/.gitignore, plugins/window_size/lib/src/platform_window.dart, plugins/window_size/lib/src/window_size_channel.dart, plugins/window_size/lib/src/window_size_utils.dart, plugins/window_size/pubspec.yaml, testbed/lib/keyboard_test_page.dart, testbed/lib/main.dart, testbed/pubspec.yaml
Makes all plugins, and the testbed, runnable in non-null mode.
=> Migrate everything to NNBD

.github/workflows/ci.yml
Required to build recently-generated projects.
=> Add new libraries to apt-get

plugins/window_size/linux/window_size_plugin.cc
The previous code used (-1, -1), which means use the requistion size (the size that GTK has determined for the window) and resulted in windows that were unresizable.
Fixes https://github.com/google/flutter-desktop-embedding/issues/844
=> [window_size] Fix incorrect value for unconstrained maximum size.

plugins/window_size/macos/Classes/FLEWindowSizePlugin.mm
- Convert the file to ObjC++
- Consolidate all the internal symbols to an anonymous namespace
- Autoformat
Fixes #855
=> [window_size] Minor macOS cleanup
